/**
 * GDS Driving School — Admin Mock Data
 * =======================================
 * Comprehensive mock data for all admin panel screens.
 */

import type {
  AdminStudent,
  AdminInstructor,
  Transaction,
  Conversation,
  ChatMessage,
  AdminSettings,
  DashboardStats,
  AdminPackage,
} from '../../store/admin/types';

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const dashboardStats: DashboardStats = {
  totalStudents: 284,
  totalInstructors: 47,
  activeLessons: 38,
  pendingApprovals: 12,
  monthlyRevenue: 8450,
  pendingPayouts: 1280,
};

// ─── Students ─────────────────────────────────────────────────────────────────

export const students: AdminStudent[] = [
  {
    id: 'STU001',
    name: 'James Wilson',
    email: 'james.wilson@email.com',
    phone: '+44 7700 900001',
    city: 'London',
    registrationDate: '2026-02-20',
    approvalStatus: 'pending',
    accountStatus: 'active',
    instructorAssigned: 'Sarah Mitchell',
    lessonsCompleted: 0,
    upcomingLessons: 0,
    rating: 0,
    avatar: 'JW',
    lessons: [],
  },
  {
    id: 'STU002',
    name: 'Emily Parker',
    email: 'emily.parker@email.com',
    phone: '+44 7700 900002',
    city: 'Manchester',
    registrationDate: '2026-02-18',
    approvalStatus: 'approved',
    accountStatus: 'active',
    instructorAssigned: 'David Thompson',
    lessonsCompleted: 12,
    upcomingLessons: 3,
    rating: 4.8,
    avatar: 'EP',
    lessons: [
      { id: 'L001', date: '2026-02-25', time: '10:00 AM', instructor: 'David Thompson', type: 'Highway Driving', status: 'upcoming', duration: '1h' },
      { id: 'L002', date: '2026-02-22', time: '2:00 PM', instructor: 'David Thompson', type: 'Parallel Parking', status: 'completed', duration: '1h' },
      { id: 'L003', date: '2026-02-20', time: '11:00 AM', instructor: 'David Thompson', type: 'City Navigation', status: 'completed', duration: '1.5h' },
    ],
  },
  {
    id: 'STU003',
    name: 'Oliver Brown',
    email: 'oliver.brown@email.com',
    phone: '+44 7700 900003',
    city: 'Birmingham',
    registrationDate: '2026-02-15',
    approvalStatus: 'approved',
    accountStatus: 'active',
    instructorAssigned: 'Sarah Mitchell',
    lessonsCompleted: 8,
    upcomingLessons: 2,
    rating: 4.5,
    avatar: 'OB',
    lessons: [
      { id: 'L004', date: '2026-02-26', time: '9:00 AM', instructor: 'Sarah Mitchell', type: 'Roundabout Practice', status: 'upcoming', duration: '1h' },
      { id: 'L005', date: '2026-02-19', time: '3:00 PM', instructor: 'Sarah Mitchell', type: 'Emergency Stop', status: 'completed', duration: '1h' },
    ],
  },
  {
    id: 'STU004',
    name: 'Sophie Taylor',
    email: 'sophie.taylor@email.com',
    phone: '+44 7700 900004',
    city: 'Leeds',
    registrationDate: '2026-02-22',
    approvalStatus: 'pending',
    accountStatus: 'active',
    instructorAssigned: 'Not Assigned',
    lessonsCompleted: 0,
    upcomingLessons: 0,
    rating: 0,
    avatar: 'ST',
    lessons: [],
  },
  {
    id: 'STU005',
    name: 'Harry Davies',
    email: 'harry.davies@email.com',
    phone: '+44 7700 900005',
    city: 'London',
    registrationDate: '2026-02-10',
    approvalStatus: 'approved',
    accountStatus: 'suspended',
    instructorAssigned: 'Michael Roberts',
    lessonsCompleted: 5,
    upcomingLessons: 0,
    rating: 3.2,
    avatar: 'HD',
    lessons: [
      { id: 'L006', date: '2026-02-08', time: '1:00 PM', instructor: 'Michael Roberts', type: 'Basic Controls', status: 'completed', duration: '1h' },
    ],
  },
  {
    id: 'STU006',
    name: 'Charlotte Evans',
    email: 'charlotte.evans@email.com',
    phone: '+44 7700 900006',
    city: 'Glasgow',
    registrationDate: '2026-02-12',
    approvalStatus: 'rejected',
    accountStatus: 'inactive',
    instructorAssigned: 'Not Assigned',
    lessonsCompleted: 0,
    upcomingLessons: 0,
    rating: 0,
    avatar: 'CE',
    lessons: [],
  },
  {
    id: 'STU007',
    name: 'George Harris',
    email: 'george.harris@email.com',
    phone: '+44 7700 900007',
    city: 'Liverpool',
    registrationDate: '2026-02-08',
    approvalStatus: 'approved',
    accountStatus: 'active',
    instructorAssigned: 'Emma Watson',
    lessonsCompleted: 20,
    upcomingLessons: 1,
    rating: 4.9,
    avatar: 'GH',
    lessons: [
      { id: 'L007', date: '2026-02-27', time: '10:00 AM', instructor: 'Emma Watson', type: 'Test Preparation', status: 'upcoming', duration: '2h' },
    ],
  },
  {
    id: 'STU008',
    name: 'Amelia Clark',
    email: 'amelia.clark@email.com',
    phone: '+44 7700 900008',
    city: 'Bristol',
    registrationDate: '2026-02-25',
    approvalStatus: 'pending',
    accountStatus: 'active',
    instructorAssigned: 'Not Assigned',
    lessonsCompleted: 0,
    upcomingLessons: 0,
    rating: 0,
    avatar: 'AC',
    lessons: [],
  },
  {
    id: 'STU009',
    name: 'Jack Robinson',
    email: 'jack.robinson@email.com',
    phone: '+44 7700 900009',
    city: 'Sheffield',
    registrationDate: '2026-02-05',
    approvalStatus: 'approved',
    accountStatus: 'active',
    instructorAssigned: 'David Thompson',
    lessonsCompleted: 15,
    upcomingLessons: 4,
    rating: 4.6,
    avatar: 'JR',
    lessons: [
      { id: 'L008', date: '2026-02-28', time: '11:00 AM', instructor: 'David Thompson', type: 'Dual Carriageway', status: 'upcoming', duration: '1.5h' },
      { id: 'L009', date: '2026-02-24', time: '9:00 AM', instructor: 'David Thompson', type: 'Night Driving', status: 'completed', duration: '1h' },
    ],
  },
  {
    id: 'STU010',
    name: 'Isabella Lewis',
    email: 'isabella.lewis@email.com',
    phone: '+44 7700 900010',
    city: 'Manchester',
    registrationDate: '2026-02-14',
    approvalStatus: 'approved',
    accountStatus: 'active',
    instructorAssigned: 'Sarah Mitchell',
    lessonsCompleted: 10,
    upcomingLessons: 2,
    rating: 4.3,
    avatar: 'IL',
    lessons: [
      { id: 'L010', date: '2026-02-27', time: '2:00 PM', instructor: 'Sarah Mitchell', type: 'Manoeuvres', status: 'upcoming', duration: '1h' },
    ],
  },
  {
    id: 'STU011',
    name: 'Thomas Walker',
    email: 'thomas.walker@email.com',
    phone: '+44 7700 900011',
    city: 'Edinburgh',
    registrationDate: '2026-02-24',
    approvalStatus: 'pending',
    accountStatus: 'active',
    instructorAssigned: 'Not Assigned',
    lessonsCompleted: 0,
    upcomingLessons: 0,
    rating: 0,
    avatar: 'TW',
    lessons: [],
  },
  {
    id: 'STU012',
    name: 'Mia Hall',
    email: 'mia.hall@email.com',
    phone: '+44 7700 900012',
    city: 'Cardiff',
    registrationDate: '2026-01-28',
    approvalStatus: 'approved',
    accountStatus: 'active',
    instructorAssigned: 'Emma Watson',
    lessonsCompleted: 22,
    upcomingLessons: 0,
    rating: 4.7,
    avatar: 'MH',
    lessons: [],
  },
  {
    id: 'STU013',
    name: 'Daniel Young',
    email: 'daniel.young@email.com',
    phone: '+44 7700 900013',
    city: 'London',
    registrationDate: '2026-02-26',
    approvalStatus: 'pending',
    accountStatus: 'active',
    instructorAssigned: 'Not Assigned',
    lessonsCompleted: 0,
    upcomingLessons: 0,
    rating: 0,
    avatar: 'DY',
    lessons: [],
  },
  {
    id: 'STU014',
    name: 'Ella King',
    email: 'ella.king@email.com',
    phone: '+44 7700 900014',
    city: 'Nottingham',
    registrationDate: '2026-02-01',
    approvalStatus: 'approved',
    accountStatus: 'active',
    instructorAssigned: 'Michael Roberts',
    lessonsCompleted: 18,
    upcomingLessons: 1,
    rating: 4.4,
    avatar: 'EK',
    lessons: [
      { id: 'L011', date: '2026-03-01', time: '10:00 AM', instructor: 'Michael Roberts', type: 'Mock Test', status: 'upcoming', duration: '2h' },
    ],
  },
  {
    id: 'STU015',
    name: 'William Green',
    email: 'william.green@email.com',
    phone: '+44 7700 900015',
    city: 'Brighton',
    registrationDate: '2026-02-16',
    approvalStatus: 'rejected',
    accountStatus: 'inactive',
    instructorAssigned: 'Not Assigned',
    lessonsCompleted: 0,
    upcomingLessons: 0,
    rating: 0,
    avatar: 'WG',
    lessons: [],
  },
];

// ─── Instructors ──────────────────────────────────────────────────────────────

export const instructors: AdminInstructor[] = [
  {
    id: 'INS001',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@email.com',
    phone: '+44 7800 100001',
    city: 'London',
    experience: '8 years',
    licenseNumber: 'ADI-2018-4521',
    documentsUploaded: [
      { id: 'D001', name: 'ADI License', type: 'license', uploadedDate: '2026-01-15', status: 'verified' },
      { id: 'D002', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2026-01-15', status: 'verified' },
      { id: 'D003', name: 'DBS Check', type: 'background', uploadedDate: '2026-01-16', status: 'verified' },
    ],
    stripeConnectionStatus: 'connected',
    stripeAccountId: 'acct_4521',
    rating: 4.9,
    completedLessons: 342,
    earningsTotal: 28560,
    pendingPayment: 1240,
    approvalStatus: 'approved',
    accountStatus: 'active',
    avatar: 'SM',
  },
  {
    id: 'INS002',
    name: 'David Thompson',
    email: 'david.thompson@email.com',
    phone: '+44 7800 100002',
    city: 'Manchester',
    experience: '5 years',
    licenseNumber: 'ADI-2021-7832',
    documentsUploaded: [
      { id: 'D004', name: 'ADI License', type: 'license', uploadedDate: '2026-01-20', status: 'verified' },
      { id: 'D005', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2026-01-20', status: 'verified' },
      { id: 'D006', name: 'DBS Check', type: 'background', uploadedDate: '2026-01-21', status: 'pending' },
    ],
    stripeConnectionStatus: 'connected',
    stripeAccountId: 'acct_7832',
    rating: 4.7,
    completedLessons: 215,
    earningsTotal: 17940,
    pendingPayment: 860,
    approvalStatus: 'approved',
    accountStatus: 'active',
    avatar: 'DT',
  },
  {
    id: 'INS003',
    name: 'Emma Watson',
    email: 'emma.watson@email.com',
    phone: '+44 7800 100003',
    city: 'Liverpool',
    experience: '10 years',
    licenseNumber: 'ADI-2016-1245',
    documentsUploaded: [
      { id: 'D007', name: 'ADI License', type: 'license', uploadedDate: '2026-01-10', status: 'verified' },
      { id: 'D008', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2026-01-10', status: 'verified' },
      { id: 'D009', name: 'DBS Check', type: 'background', uploadedDate: '2026-01-10', status: 'verified' },
    ],
    stripeConnectionStatus: 'connected',
    stripeAccountId: 'acct_1245',
    rating: 4.8,
    completedLessons: 498,
    earningsTotal: 41580,
    pendingPayment: 0,
    approvalStatus: 'approved',
    accountStatus: 'active',
    avatar: 'EW',
  },
  {
    id: 'INS004',
    name: 'Michael Roberts',
    email: 'michael.roberts@email.com',
    phone: '+44 7800 100004',
    city: 'Birmingham',
    experience: '3 years',
    licenseNumber: 'ADI-2023-9087',
    documentsUploaded: [
      { id: 'D010', name: 'ADI License', type: 'license', uploadedDate: '2026-02-01', status: 'verified' },
      { id: 'D011', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2026-02-01', status: 'pending' },
    ],
    stripeConnectionStatus: 'connected',
    stripeAccountId: 'acct_9087',
    rating: 4.3,
    completedLessons: 89,
    earningsTotal: 7420,
    pendingPayment: 520,
    approvalStatus: 'approved',
    accountStatus: 'active',
    avatar: 'MR',
  },
  {
    id: 'INS005',
    name: 'Laura Bennett',
    email: 'laura.bennett@email.com',
    phone: '+44 7800 100005',
    city: 'Leeds',
    experience: '6 years',
    licenseNumber: 'ADI-2020-3456',
    documentsUploaded: [
      { id: 'D012', name: 'ADI License', type: 'license', uploadedDate: '2026-02-10', status: 'verified' },
      { id: 'D013', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2026-02-10', status: 'verified' },
      { id: 'D014', name: 'DBS Check', type: 'background', uploadedDate: '2026-02-11', status: 'verified' },
    ],
    stripeConnectionStatus: 'connected',
    stripeAccountId: 'acct_3456',
    rating: 4.6,
    completedLessons: 178,
    earningsTotal: 14850,
    pendingPayment: 700,
    approvalStatus: 'approved',
    accountStatus: 'active',
    avatar: 'LB',
  },
  {
    id: 'INS006',
    name: 'Richard Adams',
    email: 'richard.adams@email.com',
    phone: '+44 7800 100006',
    city: 'Glasgow',
    experience: '2 years',
    licenseNumber: 'ADI-2024-6543',
    documentsUploaded: [
      { id: 'D015', name: 'ADI License', type: 'license', uploadedDate: '2026-02-20', status: 'pending' },
      { id: 'D016', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2026-02-20', status: 'pending' },
    ],
    stripeConnectionStatus: 'pending',
    stripeAccountId: 'acct_6543',
    rating: 0,
    completedLessons: 0,
    earningsTotal: 0,
    pendingPayment: 0,
    approvalStatus: 'pending',
    accountStatus: 'active',
    avatar: 'RA',
  },
  {
    id: 'INS007',
    name: 'Jessica Cooper',
    email: 'jessica.cooper@email.com',
    phone: '+44 7800 100007',
    city: 'Bristol',
    experience: '4 years',
    licenseNumber: 'ADI-2022-8765',
    documentsUploaded: [
      { id: 'D017', name: 'ADI License', type: 'license', uploadedDate: '2026-02-22', status: 'pending' },
    ],
    stripeConnectionStatus: 'not_connected',
    stripeAccountId: '',
    rating: 0,
    completedLessons: 0,
    earningsTotal: 0,
    pendingPayment: 0,
    approvalStatus: 'pending',
    accountStatus: 'active',
    avatar: 'JC',
  },
  {
    id: 'INS008',
    name: 'Andrew Phillips',
    email: 'andrew.phillips@email.com',
    phone: '+44 7800 100008',
    city: 'Sheffield',
    experience: '7 years',
    licenseNumber: 'ADI-2019-2345',
    documentsUploaded: [
      { id: 'D018', name: 'ADI License', type: 'license', uploadedDate: '2026-01-05', status: 'verified' },
      { id: 'D019', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2026-01-05', status: 'verified' },
      { id: 'D020', name: 'DBS Check', type: 'background', uploadedDate: '2026-01-06', status: 'verified' },
    ],
    stripeConnectionStatus: 'connected',
    stripeAccountId: 'acct_2345',
    rating: 4.5,
    completedLessons: 265,
    earningsTotal: 22100,
    pendingPayment: 0,
    approvalStatus: 'approved',
    accountStatus: 'suspended',
    avatar: 'AP',
  },
  {
    id: 'INS009',
    name: 'Hannah Morgan',
    email: 'hannah.morgan@email.com',
    phone: '+44 7800 100009',
    city: 'Edinburgh',
    experience: '1 year',
    licenseNumber: 'ADI-2025-5678',
    documentsUploaded: [
      { id: 'D021', name: 'ADI License', type: 'license', uploadedDate: '2026-02-24', status: 'pending' },
      { id: 'D022', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2026-02-24', status: 'pending' },
      { id: 'D023', name: 'DBS Check', type: 'background', uploadedDate: '2026-02-25', status: 'pending' },
    ],
    stripeConnectionStatus: 'pending',
    stripeAccountId: 'acct_5678',
    rating: 0,
    completedLessons: 0,
    earningsTotal: 0,
    pendingPayment: 0,
    approvalStatus: 'pending',
    accountStatus: 'active',
    avatar: 'HM',
  },
  {
    id: 'INS010',
    name: 'Christopher Lee',
    email: 'christopher.lee@email.com',
    phone: '+44 7800 100010',
    city: 'Cardiff',
    experience: '9 years',
    licenseNumber: 'ADI-2017-1357',
    documentsUploaded: [
      { id: 'D024', name: 'ADI License', type: 'license', uploadedDate: '2025-12-01', status: 'verified' },
      { id: 'D025', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2025-12-01', status: 'verified' },
      { id: 'D026', name: 'DBS Check', type: 'background', uploadedDate: '2025-12-02', status: 'verified' },
    ],
    stripeConnectionStatus: 'connected',
    stripeAccountId: 'acct_1357',
    rating: 4.4,
    completedLessons: 310,
    earningsTotal: 25870,
    pendingPayment: 1000,
    approvalStatus: 'approved',
    accountStatus: 'active',
    avatar: 'CL',
  },
  {
    id: 'INS011',
    name: 'Natalie Price',
    email: 'natalie.price@email.com',
    phone: '+44 7800 100011',
    city: 'Nottingham',
    experience: '4 years',
    licenseNumber: 'ADI-2022-2468',
    documentsUploaded: [
      { id: 'D027', name: 'ADI License', type: 'license', uploadedDate: '2026-02-26', status: 'rejected' },
    ],
    stripeConnectionStatus: 'not_connected',
    stripeAccountId: '',
    rating: 0,
    completedLessons: 0,
    earningsTotal: 0,
    pendingPayment: 0,
    approvalStatus: 'rejected',
    accountStatus: 'inactive',
    avatar: 'NP',
  },
  {
    id: 'INS012',
    name: 'Daniel Foster',
    email: 'daniel.foster@email.com',
    phone: '+44 7800 100012',
    city: 'Brighton',
    experience: '5 years',
    licenseNumber: 'ADI-2021-9753',
    documentsUploaded: [
      { id: 'D028', name: 'ADI License', type: 'license', uploadedDate: '2026-02-15', status: 'verified' },
      { id: 'D029', name: 'Insurance Certificate', type: 'insurance', uploadedDate: '2026-02-15', status: 'verified' },
      { id: 'D030', name: 'DBS Check', type: 'background', uploadedDate: '2026-02-16', status: 'verified' },
    ],
    stripeConnectionStatus: 'connected',
    stripeAccountId: 'acct_9753',
    rating: 4.2,
    completedLessons: 145,
    earningsTotal: 12100,
    pendingPayment: 0,
    approvalStatus: 'approved',
    accountStatus: 'active',
    avatar: 'DF',
  },
];

// ─── Transactions ─────────────────────────────────────────────────────────────

export const transactions: Transaction[] = [
  { id: 'TXN001', instructorId: 'INS001', instructorName: 'Sarah Mitchell', amount: 450, date: '2026-02-25', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 8' },
  { id: 'TXN002', instructorId: 'INS002', instructorName: 'David Thompson', amount: 320, date: '2026-02-25', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 8' },
  { id: 'TXN003', instructorId: 'INS003', instructorName: 'Emma Watson', amount: 580, date: '2026-02-24', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 8' },
  { id: 'TXN004', instructorId: 'INS001', instructorName: 'Sarah Mitchell', amount: 1240, date: '2026-02-27', status: 'pending', method: 'Bank Transfer', description: 'Pending payout - current period' },
  { id: 'TXN005', instructorId: 'INS002', instructorName: 'David Thompson', amount: 860, date: '2026-02-27', status: 'pending', method: 'Bank Transfer', description: 'Pending payout - current period' },
  { id: 'TXN006', instructorId: 'INS004', instructorName: 'Michael Roberts', amount: 520, date: '2026-02-27', status: 'pending', method: 'Bank Transfer', description: 'Pending payout - current period' },
  { id: 'TXN007', instructorId: 'INS005', instructorName: 'Laura Bennett', amount: 700, date: '2026-02-27', status: 'pending', method: 'Bank Transfer', description: 'Pending payout - current period' },
  { id: 'TXN008', instructorId: 'INS010', instructorName: 'Christopher Lee', amount: 1000, date: '2026-02-27', status: 'pending', method: 'Bank Transfer', description: 'Pending payout - current period' },
  { id: 'TXN009', instructorId: 'INS003', instructorName: 'Emma Watson', amount: 420, date: '2026-02-18', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 7' },
  { id: 'TXN010', instructorId: 'INS001', instructorName: 'Sarah Mitchell', amount: 380, date: '2026-02-18', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 7' },
  { id: 'TXN011', instructorId: 'INS005', instructorName: 'Laura Bennett', amount: 290, date: '2026-02-18', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 7' },
  { id: 'TXN012', instructorId: 'INS004', instructorName: 'Michael Roberts', amount: 210, date: '2026-02-17', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 7' },
  { id: 'TXN013', instructorId: 'INS010', instructorName: 'Christopher Lee', amount: 440, date: '2026-02-17', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 7' },
  { id: 'TXN014', instructorId: 'INS002', instructorName: 'David Thompson', amount: 350, date: '2026-02-11', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 6' },
  { id: 'TXN015', instructorId: 'INS001', instructorName: 'Sarah Mitchell', amount: 490, date: '2026-02-11', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 6' },
  { id: 'TXN016', instructorId: 'INS003', instructorName: 'Emma Watson', amount: 510, date: '2026-02-11', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 6' },
  { id: 'TXN017', instructorId: 'INS012', instructorName: 'Daniel Foster', amount: 275, date: '2026-02-10', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 6' },
  { id: 'TXN018', instructorId: 'INS008', instructorName: 'Andrew Phillips', amount: 360, date: '2026-02-04', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 5' },
  { id: 'TXN019', instructorId: 'INS005', instructorName: 'Laura Bennett', amount: 310, date: '2026-02-04', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 5' },
  { id: 'TXN020', instructorId: 'INS010', instructorName: 'Christopher Lee', amount: 400, date: '2026-02-04', status: 'paid', method: 'Bank Transfer', description: 'Weekly payout - Week 5' },
];

// ─── Conversations ────────────────────────────────────────────────────────────

export const conversations: Conversation[] = [
  {
    id: 'CONV001',
    instructorId: 'INS001',
    instructorName: 'Sarah Mitchell',
    instructorAvatar: 'SM',
    lastMessage: 'Hi, I need help with updating my availability schedule for next week.',
    timestamp: '10:30 AM',
    unreadCount: 2,
    status: 'unread',
  },
  {
    id: 'CONV002',
    instructorId: 'INS002',
    instructorName: 'David Thompson',
    instructorAvatar: 'DT',
    lastMessage: 'Thank you for resolving the payment issue. Much appreciated!',
    timestamp: '9:15 AM',
    unreadCount: 0,
    status: 'read',
  },
  {
    id: 'CONV003',
    instructorId: 'INS004',
    instructorName: 'Michael Roberts',
    instructorAvatar: 'MR',
    lastMessage: 'When will my pending payment be processed? It has been over a week now.',
    timestamp: 'Yesterday',
    unreadCount: 1,
    status: 'unread',
  },
  {
    id: 'CONV004',
    instructorId: 'INS005',
    instructorName: 'Laura Bennett',
    instructorAvatar: 'LB',
    lastMessage: 'I have uploaded my updated insurance certificate. Please verify.',
    timestamp: 'Yesterday',
    unreadCount: 3,
    status: 'unread',
  },
  {
    id: 'CONV005',
    instructorId: 'INS010',
    instructorName: 'Christopher Lee',
    instructorAvatar: 'CL',
    lastMessage: 'All good now, thanks for the quick response.',
    timestamp: '2 days ago',
    unreadCount: 0,
    status: 'resolved',
  },
  {
    id: 'CONV006',
    instructorId: 'INS012',
    instructorName: 'Daniel Foster',
    instructorAvatar: 'DF',
    lastMessage: 'Can I get a breakdown of the commission charges for January?',
    timestamp: '3 days ago',
    unreadCount: 0,
    status: 'read',
  },
];

// ─── Chat Messages ────────────────────────────────────────────────────────────

export const chatMessages: ChatMessage[] = [
  // CONV001 - Sarah Mitchell
  { id: 'MSG001', conversationId: 'CONV001', senderId: 'INS001', senderType: 'instructor', text: 'Hi, I need help with updating my availability schedule for next week.', timestamp: '10:30 AM', seen: true },
  { id: 'MSG002', conversationId: 'CONV001', senderId: 'INS001', senderType: 'instructor', text: 'The system is not letting me add slots for Saturday.', timestamp: '10:31 AM', seen: false },

  // CONV002 - David Thompson
  { id: 'MSG003', conversationId: 'CONV002', senderId: 'INS002', senderType: 'instructor', text: 'Hi, my last payment seems to be incorrect. Can you check?', timestamp: '8:45 AM', seen: true },
  { id: 'MSG004', conversationId: 'CONV002', senderId: 'ADMIN', senderType: 'admin', text: 'Hi David, let me look into that for you. Which payment period are you referring to?', timestamp: '8:52 AM', seen: true },
  { id: 'MSG005', conversationId: 'CONV002', senderId: 'INS002', senderType: 'instructor', text: 'The payout from Week 7. The amount was lower than expected.', timestamp: '9:00 AM', seen: true },
  { id: 'MSG006', conversationId: 'CONV002', senderId: 'ADMIN', senderType: 'admin', text: 'I see the issue. The commission rate was applied twice. I have corrected it and the difference will be added to your next payout.', timestamp: '9:10 AM', seen: true },
  { id: 'MSG007', conversationId: 'CONV002', senderId: 'INS002', senderType: 'instructor', text: 'Thank you for resolving the payment issue. Much appreciated!', timestamp: '9:15 AM', seen: true },

  // CONV003 - Michael Roberts
  { id: 'MSG008', conversationId: 'CONV003', senderId: 'INS004', senderType: 'instructor', text: 'Hi, I wanted to ask about my pending payment status.', timestamp: 'Yesterday 2:00 PM', seen: true },
  { id: 'MSG009', conversationId: 'CONV003', senderId: 'ADMIN', senderType: 'admin', text: 'Hi Michael, pending payments are processed every Friday. Yours should be cleared by this week.', timestamp: 'Yesterday 2:15 PM', seen: true },
  { id: 'MSG010', conversationId: 'CONV003', senderId: 'INS004', senderType: 'instructor', text: 'When will my pending payment be processed? It has been over a week now.', timestamp: 'Yesterday 4:30 PM', seen: false },

  // CONV004 - Laura Bennett
  { id: 'MSG011', conversationId: 'CONV004', senderId: 'INS005', senderType: 'instructor', text: 'Hello, I need to update my insurance documents.', timestamp: 'Yesterday 11:00 AM', seen: true },
  { id: 'MSG012', conversationId: 'CONV004', senderId: 'ADMIN', senderType: 'admin', text: 'Sure, you can upload them from your profile settings under Documents.', timestamp: 'Yesterday 11:20 AM', seen: true },
  { id: 'MSG013', conversationId: 'CONV004', senderId: 'INS005', senderType: 'instructor', text: 'Done! I have uploaded them.', timestamp: 'Yesterday 1:00 PM', seen: true },
  { id: 'MSG014', conversationId: 'CONV004', senderId: 'INS005', senderType: 'instructor', text: 'I have uploaded my updated insurance certificate. Please verify.', timestamp: 'Yesterday 1:01 PM', seen: false },

  // CONV005 - Christopher Lee
  { id: 'MSG015', conversationId: 'CONV005', senderId: 'INS010', senderType: 'instructor', text: 'Is there a way to see my student reviews in the app?', timestamp: '2 days ago 9:00 AM', seen: true },
  { id: 'MSG016', conversationId: 'CONV005', senderId: 'ADMIN', senderType: 'admin', text: 'Yes, go to your Dashboard and scroll down to the Reviews section. Let me know if you need further help.', timestamp: '2 days ago 9:30 AM', seen: true },
  { id: 'MSG017', conversationId: 'CONV005', senderId: 'INS010', senderType: 'instructor', text: 'All good now, thanks for the quick response.', timestamp: '2 days ago 10:00 AM', seen: true },

  // CONV006 - Daniel Foster
  { id: 'MSG018', conversationId: 'CONV006', senderId: 'INS012', senderType: 'instructor', text: 'Can I get a breakdown of the commission charges for January?', timestamp: '3 days ago 3:00 PM', seen: true },
  { id: 'MSG019', conversationId: 'CONV006', senderId: 'ADMIN', senderType: 'admin', text: 'Of course. I will send you the detailed report by end of day. The total commission was 12% of your gross earnings.', timestamp: '3 days ago 3:45 PM', seen: true },
];

// ─── Default Settings ─────────────────────────────────────────────────────────

export const defaultSettings: AdminSettings = {
  lessonPricingDefault: 35,
  platformFees: 2.5,
  emailNotifications: true,
  pushNotifications: true,
  smsAlerts: false,
};

// ─── Admin Packages ───────────────────────────────────────────────────────────

export const adminPackages: AdminPackage[] = [
  {
    id: 'APKG001',
    instructorId: 'INS001',
    instructorName: 'Sarah Mitchell',
    title: 'Beginner Essentials',
    description: '10 lessons covering all basic driving skills',
    lessonCount: 10,
    price: 300,
    commissionPercentage: 12,
    status: 'approved',
    createdAt: '2026-02-01',
  },
  {
    id: 'APKG002',
    instructorId: 'INS001',
    instructorName: 'Sarah Mitchell',
    title: 'Test Preparation Intensive',
    description: '5 intensive sessions focused on driving test preparation',
    lessonCount: 5,
    price: 175,
    commissionPercentage: 15,
    status: 'approved',
    createdAt: '2026-02-05',
  },
  {
    id: 'APKG003',
    instructorId: 'INS002',
    instructorName: 'David Thompson',
    title: 'Highway Mastery',
    description: '8 lessons for confident motorway and A-road driving',
    lessonCount: 8,
    price: 260,
    commissionPercentage: 12,
    status: 'pending',
    createdAt: '2026-02-20',
  },
  {
    id: 'APKG004',
    instructorId: 'INS003',
    instructorName: 'Emma Watson',
    title: 'Complete Learner Bundle',
    description: '20 lessons from beginner to test-ready',
    lessonCount: 20,
    price: 550,
    commissionPercentage: 10,
    status: 'approved',
    createdAt: '2026-01-15',
  },
  {
    id: 'APKG005',
    instructorId: 'INS004',
    instructorName: 'Michael Roberts',
    title: 'Refresher Course',
    description: '3 lessons for returning drivers needing a confidence boost',
    lessonCount: 3,
    price: 105,
    commissionPercentage: 15,
    status: 'pending',
    createdAt: '2026-02-22',
  },
  {
    id: 'APKG006',
    instructorId: 'INS005',
    instructorName: 'Laura Bennett',
    title: 'Night Driving Special',
    description: '4 evening lessons focusing on night driving skills',
    lessonCount: 4,
    price: 140,
    commissionPercentage: 12,
    status: 'pending',
    createdAt: '2026-02-25',
  },
  {
    id: 'APKG007',
    instructorId: 'INS010',
    instructorName: 'Christopher Lee',
    title: 'Advanced Techniques',
    description: '6 lessons covering advanced driving techniques',
    lessonCount: 6,
    price: 210,
    commissionPercentage: 10,
    status: 'approved',
    createdAt: '2026-02-10',
  },
  {
    id: 'APKG008',
    instructorId: 'INS012',
    instructorName: 'Daniel Foster',
    title: 'City Navigation Package',
    description: '5 urban driving focused lessons',
    lessonCount: 5,
    price: 150,
    commissionPercentage: 12,
    status: 'rejected',
    createdAt: '2026-02-18',
  },
];
